apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: typesense-operator
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense-operator
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: typesense-operator
    spec:
      serviceAccountName: typesense-operator-sa
      containers:
        - name: typesense-operator
          image: "{{ .Values.image.typesenseImage }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
