apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typesenseoperator-role-cluster
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get, create]
  - apiGroups: [typesenseproject.org]
    resources: [typesenseoperators]
    verbs: [list, watch, create, update, patch, delete]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: ["*"]
    resources: [namespaces,configmaps,statefulsets,services,secrets]
    verbs: [list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: typesenseoperator-role-namespaced
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [typesenseproject.org]
    resources: [typesenseoperators]
    verbs: [list, watch, patch, create, update, delete]
  - apiGroups: ["*"]
    resources: [namespaces,configmaps,statefulsets,services,pods,events,secrets]
    verbs: [list, watch, create, update, patch, delete, get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typesenseoperator-crolebinding-cluster
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typesenseoperator-role-cluster
subjects:
  - kind: ServiceAccount
    name: typesense-operator-sa
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: typesenseoperator-rolebinding-namespaced
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: typesenseoperator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: typesense-operator-sa
    namespace: {{ .Values.namespace }}